opt_in_rules:
- anyobject_protocol
- array_init
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- empty_count
- empty_string
- empty_xctest_method
- explicit_enum_raw_value
- explicit_init
- fatal_error_message
- file_header
- first_where
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- modifier_order
- multiline_arguments
- multiline_parameters
- nimble_operator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- private_outlet
- prohibited_super_call
- protocol_property_accessors_order
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- sorted_imports
- switch_case_on_newline
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition

disabled_rules:
- explicit_enum_raw_value

excluded:
- Pods
- Frameworks
- iOS-UITests/SnapshotHelper.swift
- Common/R.generated.swift
- iOS/R.generated.swift

line_length: 160

identifier_name:
  excluded:
    - id

trailing_comma:
  mandatory_comma: true

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/  Created for xikolo-ios under MIT license\.
                    \/\/  Copyright © HPI\. All rights reserved\.
                    \/\/

custom_rules:
  closing_brace_whitespace:
    included: ".*.swift"
    regex: '(?:\n| {2,})\}\)? *\n *(?!set |set\(|case |default)[^ \n\})\]\#\/]'
    name: "Closing Brace Whitespace"
    message: "Empty line required after closing curly braces if code with same indentation follows."
    severity: warning
  closure_params_parantheses:
    included: ".*.swift"
    regex: '\{\s*\([^):]+\)\s*in'
    name: "Unnecessary Closure Params Parantheses"
    message: "Don't use parantheses around non-typed parameters in a closure."
    severity: warning
  late_force_unwrapping:
    included: ".*.swift"
    regex: '\(\S+\?\.\S+\)!'
    name: "Late Force Unwrapping"
    message: "Don't use ? first to force unwrap later – directly unwrap within the parantheses."
    severity: warning
  unnecessary_nil_assignment:
    included: ".*.swift"
    regex: 'var \S+\s*:\s*[^\s]+\?\s*=\s*nil'
    name: "Unnecessary Nil Assignment"
    message: "Don't assign nil as a value when defining an optional type – it's nil by default."
    severity: warning
  whitespace_comment_start:
    included: ".*.swift"
    regex: '[^:]\/\/[^\s\/]'
    name: "Whitespace Comment Start"
    message: "A comment should always start with a whitespace."
    severity: warning
